name: transfuser
channels:
  - defaults
dependencies:
  - pip
  - python=3.11
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - cudatoolkit
  - pip:
    - -r team_code_transfuser/requirements.txt
    - mmsegmentation==0.25.0
    - mmdet==2.25.0
